# Generated by Django 2.1.4 on 2019-08-21 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_show', models.IntegerField(default=1)),
                ('sort', models.IntegerField(default=1)),
                ('type', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'banners',
            },
        ),
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('pid', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=1)),
                ('top_id', models.IntegerField(default=1)),
                ('is_recommend', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'cate',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('describe', models.TextField()),
                ('content', models.TextField()),
                ('picture', models.CharField(max_length=255)),
                ('storage', models.IntegerField(default=0)),
                ('lock_storage', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_recommend', models.IntegerField(default=1)),
                ('top_id', models.IntegerField()),
                ('t_comment', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Cate')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('is_show', models.IntegerField(default=1)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Sadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('is_admin', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sadmin',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('is_recommend', models.IntegerField(default=1)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Cate')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('image', models.CharField(default='', max_length=255)),
                ('signator', models.CharField(default='', max_length=255)),
                ('is_valid', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Tags'),
        ),
    ]
