# Generated by Django 2.1.4 on 2019-08-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cate',
            name='picture',
            field=models.CharField(default='', max_length=255),
        ),
    ]
