# Generated by Django 2.1.4 on 2019-08-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20190829_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('good_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('count', models.IntegerField()),
                ('picture', models.CharField(max_length=255)),
                ('good_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
