# Generated by Django 2.1.4 on 2019-09-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20190903_1623'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order_detail',
            table='order_detail',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
    ]
