# Generated by Django 2.1.4 on 2019-09-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20190905_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
