# Generated by Django 2.1.4 on 2019-09-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20190905_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=models.IntegerField(max_length=13),
        ),
    ]
